# .readthedocs.yaml
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_install:
      # https://github.com/pdm-project/pdm/discussions/1365
      - pip install --upgrade pdm
      - VIRTUAL_ENV=$(dirname $(dirname $(which python))) pdm install --with docs

mkdocs:
  configuration: mkdocs.yml