strict: true

site_name: "Hawk: Debug & Profile"

site_author: Roman Hlushko
site_description: A nimble and powerful Python debugging and profiling in production
site_url: https://hawk-debug.readthedocs.io/

copyright: Copyright &copy; 2024 - Present, <a target="_blank" href="https://www.romaglushko.com/">Roman Hlushko</a> - <a href="#__consent">Change cookie settings</a>

theme:
  name: material
  icon:
    logo: material/pause
    repo: fontawesome/brands/github
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: deep orange
    accent: amber
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: deep orange
    accent: amber
    toggle:
      icon: material/weather-night
      name: Switch to dark mode

  features:
    - navigation.sections

  font:
    text: Roboto
    code: Roboto Mono

repo_name: roma-glushko/hawk
repo_url: https://github.com/roma-glushko/hawk
edit_uri: ''

plugins:
- search

markdown_extensions:
- toc:
    permalink: true
- admonition
- pymdownx.details
- pymdownx.superfences
- mkautodoc
- markdown.extensions.codehilite:
    guess_lang: false
- mdx_include:
    base_path: docs
- codehilite
- md_in_html
- attr_list
- pymdownx.emoji:
    emoji_generator: !!python/name:materialx.emoji.to_svg
    emoji_index: !!python/name:materialx.emoji.twemoji
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format ''
- pymdownx.tabbed:
    alternate_style: true

extra:
    consent:
        title: Cookie consent
        description: "We use cookies to recognize your repeated visits and preferences, as well as to measure the effectiveness of our documentation and whether users find what they're searching for. With your consent, you're helping us to make our documentation better."
nav:
- Getting Started: index.md
- Env Vars: env-variables.md
- Profiling:
    - Intro: profiling/index.md
    - CPU: profiling/cpu.md
    - Memory: profiling/memory.md
    - Miscellaneous: profiling/misc.md
- Debug Vars: debug-variables.md
- ZPages: zpages.md
- Integrations:
  - FastAPI: integrations/fastapi.md
  - Starlette: integrations/starlette.md
  - Flask: integrations/flask.md