---
name: Publish Package

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*.*'
jobs:
  publish:
    name: Publish Package to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.9"

      - uses: pdm-project/setup-pdm@v4

      - name: Install dependencies
        run: pdm install

      - name: Publish Package
        run: make build

      - name: Check Git Status
        run: git status

      - name: Publish Package
        run: make publish